services:
  app:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
      - FLASK_ENV=${FLASK_ENV:-production}
      - PORT=5000
      - BRAVE_API_KEY=${BRAVE_API_KEY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
