# Standard excludes for Python projects
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 79
indent-width = 4
target-version = "py312"  # Using more stable Python version

[lint]
# Extended rule selection
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "D",   # pydocstyle
    "C901", # McCabe complexity
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "Q",   # flake8-quotes
    "RUF", # Ruff-specific rules
    "B",   # flake8-bugbear
    "ISC", # implicit-str-concat
]

# Ignore rules that conflict with Google Style
ignore = [
    "D203",  # one-blank-line-before-class
    "D213",  # multi-line-summary-second-line
    "D406",  # section-name-ends-in-colon
    "D407",  # dashed-underline-after-section
    "E203",  # whitespace before ':'
]

fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pydocstyle]
convention = "google"
allow-no-section = false

[lint.pep8-naming]
classmethod-decorators = [
    "classmethod",
    "pyclbr.classmethod",
    "staticmethod"
]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"

[lint.per-file-ignores]
"__init__.py" = ["F401"]    # Unused imports in __init__.py
"tests/*" = ["D"]           # No docstring requirements in tests
"conftest.py" = ["D"]       # No docstring requirements in pytest conftest
"test_*.py" = ["D"]         # No docstring requirements in test files

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

# Preview future formatter (optional, remove if not needed)
[lint.format]
preview = true
